### ISSUE TITLE
Flow problem

### ISSUE THREAD

**Issue by maceide** [shaarkys/no.jonkristian.octoprint#1]
Hi, until recently, my old flows for sending push notifications with a snapshot of the print when finished were working flawlessly. All of a sudden, they don't work anymore, and I can't find the snapshot image in the Homey flow configurator. Has this feature been removed?

Regards,
Andreas

**Comment by shaarkys** [comment]
Hi,
sorry, seems I'm not getting notifications on Issues created. Is this still an issue ? Can you share example of that flow you mentioned ? Thank you.

**Comment by shaarkys** [comment]
Example which works for me : 

![flow](https://github.com/user-attachments/assets/71854fbc-398b-405b-ab11-069de439e3fb)

It if doesn't, please submit diag. log and reopen this issue, if needed.
